/* File generated by the BNF Converter (bnfc 2.9.4). */

#ifndef PARSER_HEADER_FILE
#define PARSER_HEADER_FILE

#include <stdio.h>
#include "Absyn.h"

Progr  pProgr(FILE *inp);
Progr psProgr(const char *str);
BlocoDec  pBlocoDec(FILE *inp);
BlocoDec psBlocoDec(const char *str);
BlocoConstante  pBlocoConstante(FILE *inp);
BlocoConstante psBlocoConstante(const char *str);
RegraConstante  pRegraConstante(FILE *inp);
RegraConstante psRegraConstante(const char *str);
RegraDec  pRegraDec(FILE *inp);
RegraDec psRegraDec(const char *str);
BlocoVar  pBlocoVar(FILE *inp);
BlocoVar psBlocoVar(const char *str);
RegraDecVar  pRegraDecVar(FILE *inp);
RegraDecVar psRegraDecVar(const char *str);
BlocoType  pBlocoType(FILE *inp);
BlocoType psBlocoType(const char *str);
RegraType  pRegraType(FILE *inp);
RegraType psRegraType(const char *str);
RegraDecVetor  pRegraDecVetor(FILE *inp);
RegraDecVetor psRegraDecVetor(const char *str);
RegraDecStruct  pRegraDecStruct(FILE *inp);
RegraDecStruct psRegraDecStruct(const char *str);
BlocoStmt  pBlocoStmt(FILE *inp);
BlocoStmt psBlocoStmt(const char *str);
RegraStmt  pRegraStmt(FILE *inp);
RegraStmt psRegraStmt(const char *str);
Stmt  pStmt(FILE *inp);
Stmt psStmt(const char *str);
Atribuicao  pAtribuicao(FILE *inp);
Atribuicao psAtribuicao(const char *str);
AtribuicaoVetor  pAtribuicaoVetor(FILE *inp);
AtribuicaoVetor psAtribuicaoVetor(const char *str);
AtribuicaoStruct  pAtribuicaoStruct(FILE *inp);
AtribuicaoStruct psAtribuicaoStruct(const char *str);
Valor  pValor(FILE *inp);
Valor psValor(const char *str);
RExpr  pRExpr(FILE *inp);
RExpr psRExpr(const char *str);
Opa  pOpa(FILE *inp);
Opa psOpa(const char *str);
Opa  pOpa1(FILE *inp);
Opa psOpa1(const char *str);
Opa  pOpa2(FILE *inp);
Opa psOpa2(const char *str);
ExpressaoLogica  pExpressaoLogica(FILE *inp);
ExpressaoLogica psExpressaoLogica(const char *str);
If  pIf(FILE *inp);
If psIf(const char *str);
IfStmt  pIfStmt(FILE *inp);
IfStmt psIfStmt(const char *str);
ElseStmt  pElseStmt(FILE *inp);
ElseStmt psElseStmt(const char *str);
ElsIfStmt  pElsIfStmt(FILE *inp);
ElsIfStmt psElsIfStmt(const char *str);
While  pWhile(FILE *inp);
While psWhile(const char *str);
For  pFor(FILE *inp);
For psFor(const char *str);
Case  pCase(FILE *inp);
Case psCase(const char *str);
CaseStmt  pCaseStmt(FILE *inp);
CaseStmt psCaseStmt(const char *str);
Type  pType(FILE *inp);
Type psType(const char *str);
OperadoresLogicos  pOperadoresLogicos(FILE *inp);
OperadoresLogicos psOperadoresLogicos(const char *str);
ConectivosLogicos  pConectivosLogicos(FILE *inp);
ConectivosLogicos psConectivosLogicos(const char *str);

#endif
