/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printProgr(Progr p)
{
  visitProgr(p);
  _n_ = 0;
  bufReset();
  ppProgr(p, 0);
  return buf_;
}
char *printBlocoDec(BlocoDec p)
{
  _n_ = 0;
  bufReset();
  ppBlocoDec(p, 0);
  return buf_;
}
char *printBlocoConstante(BlocoConstante p)
{
  _n_ = 0;
  bufReset();
  ppBlocoConstante(p, 0);
  return buf_;
}
char *printRegraConstante(RegraConstante p)
{
  _n_ = 0;
  bufReset();
  ppRegraConstante(p, 0);
  return buf_;
}
char *printRegraDec(RegraDec p)
{
  _n_ = 0;
  bufReset();
  ppRegraDec(p, 0);
  return buf_;
}
char *printBlocoVar(BlocoVar p)
{
  _n_ = 0;
  bufReset();
  ppBlocoVar(p, 0);
  return buf_;
}
char *printRegraDecVar(RegraDecVar p)
{
  _n_ = 0;
  bufReset();
  ppRegraDecVar(p, 0);
  return buf_;
}
char *printBlocoType(BlocoType p)
{
  _n_ = 0;
  bufReset();
  ppBlocoType(p, 0);
  return buf_;
}
char *printRegraType(RegraType p)
{
  _n_ = 0;
  bufReset();
  ppRegraType(p, 0);
  return buf_;
}
char *printRegraDecVetor(RegraDecVetor p)
{
  _n_ = 0;
  bufReset();
  ppRegraDecVetor(p, 0);
  return buf_;
}
char *printRegraDecStruct(RegraDecStruct p)
{
  _n_ = 0;
  bufReset();
  ppRegraDecStruct(p, 0);
  return buf_;
}
char *printBlocoStmt(BlocoStmt p)
{
  _n_ = 0;
  bufReset();
  ppBlocoStmt(p, 0);
  return buf_;
}
char *printRegraStmt(RegraStmt p)
{
  _n_ = 0;
  bufReset();
  ppRegraStmt(p, 0);
  return buf_;
}
char *printStmt(Stmt p)
{
  _n_ = 0;
  bufReset();
  ppStmt(p, 0);
  return buf_;
}
char *printAtribuicao(Atribuicao p)
{
  _n_ = 0;
  bufReset();
  ppAtribuicao(p, 0);
  return buf_;
}
char *printAtribuicaoVetor(AtribuicaoVetor p)
{
  _n_ = 0;
  bufReset();
  ppAtribuicaoVetor(p, 0);
  return buf_;
}
char *printAtribuicaoStruct(AtribuicaoStruct p)
{
  _n_ = 0;
  bufReset();
  ppAtribuicaoStruct(p, 0);
  return buf_;
}
char *printValor(Valor p)
{
  _n_ = 0;
  bufReset();
  ppValor(p, 0);
  return buf_;
}
char *printRExpr(RExpr p)
{
  _n_ = 0;
  bufReset();
  ppRExpr(p, 0);
  return buf_;
}
char *printOpa(Opa p)
{
  _n_ = 0;
  bufReset();
  ppOpa(p, 0);
  return buf_;
}
char *printExpressaoLogica(ExpressaoLogica p)
{
  _n_ = 0;
  bufReset();
  ppExpressaoLogica(p, 0);
  return buf_;
}
char *printIf(If p)
{
  _n_ = 0;
  bufReset();
  ppIf(p, 0);
  return buf_;
}
char *printIfStmt(IfStmt p)
{
  _n_ = 0;
  bufReset();
  ppIfStmt(p, 0);
  return buf_;
}
char *printElseStmt(ElseStmt p)
{
  _n_ = 0;
  bufReset();
  ppElseStmt(p, 0);
  return buf_;
}
char *printElsIfStmt(ElsIfStmt p)
{
  _n_ = 0;
  bufReset();
  ppElsIfStmt(p, 0);
  return buf_;
}
char *printWhile(While p)
{
  _n_ = 0;
  bufReset();
  ppWhile(p, 0);
  return buf_;
}
char *printFor(For p)
{
  _n_ = 0;
  bufReset();
  ppFor(p, 0);
  return buf_;
}
char *printCase(Case p)
{
  _n_ = 0;
  bufReset();
  ppCase(p, 0);
  return buf_;
}
char *printCaseStmt(CaseStmt p)
{
  _n_ = 0;
  bufReset();
  ppCaseStmt(p, 0);
  return buf_;
}
char *printType(Type p)
{
  _n_ = 0;
  bufReset();
  ppType(p, 0);
  return buf_;
}
char *printOperadoresLogicos(OperadoresLogicos p)
{
  _n_ = 0;
  bufReset();
  ppOperadoresLogicos(p, 0);
  return buf_;
}
char *printConectivosLogicos(ConectivosLogicos p)
{
  _n_ = 0;
  bufReset();
  ppConectivosLogicos(p, 0);
  return buf_;
}
char *showProgr(Progr p)
{
  _n_ = 0;
  bufReset();
  shProgr(p);
  return buf_;
}
char *showBlocoDec(BlocoDec p)
{
  _n_ = 0;
  bufReset();
  shBlocoDec(p);
  return buf_;
}
char *showBlocoConstante(BlocoConstante p)
{
  _n_ = 0;
  bufReset();
  shBlocoConstante(p);
  return buf_;
}
char *showRegraConstante(RegraConstante p)
{
  _n_ = 0;
  bufReset();
  shRegraConstante(p);
  return buf_;
}
char *showRegraDec(RegraDec p)
{
  _n_ = 0;
  bufReset();
  shRegraDec(p);
  return buf_;
}
char *showBlocoVar(BlocoVar p)
{
  _n_ = 0;
  bufReset();
  shBlocoVar(p);
  return buf_;
}
char *showRegraDecVar(RegraDecVar p)
{
  _n_ = 0;
  bufReset();
  shRegraDecVar(p);
  return buf_;
}
char *showBlocoType(BlocoType p)
{
  _n_ = 0;
  bufReset();
  shBlocoType(p);
  return buf_;
}
char *showRegraType(RegraType p)
{
  _n_ = 0;
  bufReset();
  shRegraType(p);
  return buf_;
}
char *showRegraDecVetor(RegraDecVetor p)
{
  _n_ = 0;
  bufReset();
  shRegraDecVetor(p);
  return buf_;
}
char *showRegraDecStruct(RegraDecStruct p)
{
  _n_ = 0;
  bufReset();
  shRegraDecStruct(p);
  return buf_;
}
char *showBlocoStmt(BlocoStmt p)
{
  _n_ = 0;
  bufReset();
  shBlocoStmt(p);
  return buf_;
}
char *showRegraStmt(RegraStmt p)
{
  _n_ = 0;
  bufReset();
  shRegraStmt(p);
  return buf_;
}
char *showStmt(Stmt p)
{
  _n_ = 0;
  bufReset();
  shStmt(p);
  return buf_;
}
char *showAtribuicao(Atribuicao p)
{
  _n_ = 0;
  bufReset();
  shAtribuicao(p);
  return buf_;
}
char *showAtribuicaoVetor(AtribuicaoVetor p)
{
  _n_ = 0;
  bufReset();
  shAtribuicaoVetor(p);
  return buf_;
}
char *showAtribuicaoStruct(AtribuicaoStruct p)
{
  _n_ = 0;
  bufReset();
  shAtribuicaoStruct(p);
  return buf_;
}
char *showValor(Valor p)
{
  _n_ = 0;
  bufReset();
  shValor(p);
  return buf_;
}
char *showRExpr(RExpr p)
{
  _n_ = 0;
  bufReset();
  shRExpr(p);
  return buf_;
}
char *showOpa(Opa p)
{
  _n_ = 0;
  bufReset();
  shOpa(p);
  return buf_;
}
char *showExpressaoLogica(ExpressaoLogica p)
{
  _n_ = 0;
  bufReset();
  shExpressaoLogica(p);
  return buf_;
}
char *showIf(If p)
{
  _n_ = 0;
  bufReset();
  shIf(p);
  return buf_;
}
char *showIfStmt(IfStmt p)
{
  _n_ = 0;
  bufReset();
  shIfStmt(p);
  return buf_;
}
char *showElseStmt(ElseStmt p)
{
  _n_ = 0;
  bufReset();
  shElseStmt(p);
  return buf_;
}
char *showElsIfStmt(ElsIfStmt p)
{
  _n_ = 0;
  bufReset();
  shElsIfStmt(p);
  return buf_;
}
char *showWhile(While p)
{
  _n_ = 0;
  bufReset();
  shWhile(p);
  return buf_;
}
char *showFor(For p)
{
  _n_ = 0;
  bufReset();
  shFor(p);
  return buf_;
}
char *showCase(Case p)
{
  _n_ = 0;
  bufReset();
  shCase(p);
  return buf_;
}
char *showCaseStmt(CaseStmt p)
{
  _n_ = 0;
  bufReset();
  shCaseStmt(p);
  return buf_;
}
char *showType(Type p)
{
  _n_ = 0;
  bufReset();
  shType(p);
  return buf_;
}
char *showOperadoresLogicos(OperadoresLogicos p)
{
  _n_ = 0;
  bufReset();
  shOperadoresLogicos(p);
  return buf_;
}
char *showConectivosLogicos(ConectivosLogicos p)
{
  _n_ = 0;
  bufReset();
  shConectivosLogicos(p);
  return buf_;
}
void ppProgr(Progr p, int _i_)
{
  switch(p->kind)
  {
  case is_Program:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("MODULE");
    ppIdent(p->u.program_.ident_1, 0);
    renderC(';');
    ppBlocoDec(p->u.program_.blocodec_, 0);
    renderS("BEGIN");
    ppRegraStmt(p->u.program_.regrastmt_, 0);
    renderS("END");
    ppIdent(p->u.program_.ident_2, 0);
    renderC('.');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Progr!\n");
    exit(1);
  }
}

void ppBlocoDec(BlocoDec p, int _i_)
{
  switch(p->kind)
  {
  case is_BlocoDec1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppBlocoConstante(p->u.blocodec1_.blococonstante_, 0);
    ppBlocoDec(p->u.blocodec1_.blocodec_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_BlocoDec2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppBlocoVar(p->u.blocodec2_.blocovar_, 0);
    ppBlocoDec(p->u.blocodec2_.blocodec_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_BlocoDec3:
    if (_i_ > 0) renderC(_L_PAREN);
    ppBlocoType(p->u.blocodec3_.blocotype_, 0);
    ppBlocoDec(p->u.blocodec3_.blocodec_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_BlocoDec_:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing BlocoDec!\n");
    exit(1);
  }
}

void ppBlocoConstante(BlocoConstante p, int _i_)
{
  switch(p->kind)
  {
  case is_BlocoConstante1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("CONST");
    ppRegraConstante(p->u.blococonstante1_.regraconstante_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing BlocoConstante!\n");
    exit(1);
  }
}

void ppRegraConstante(RegraConstante p, int _i_)
{
  switch(p->kind)
  {
  case is_RegraConstante1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.regraconstante1_.ident_, 0);
    renderC(':');
    ppType(p->u.regraconstante1_.type_, 0);
    renderC('=');
    ppValor(p->u.regraconstante1_.valor_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_RegraConstante2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.regraconstante2_.ident_, 0);
    renderC(':');
    ppType(p->u.regraconstante2_.type_, 0);
    renderC('=');
    ppValor(p->u.regraconstante2_.valor_, 0);
    renderC(';');
    ppRegraConstante(p->u.regraconstante2_.regraconstante_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RegraConstante!\n");
    exit(1);
  }
}

void ppRegraDec(RegraDec p, int _i_)
{
  switch(p->kind)
  {
  case is_RegraDec1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.regradec1_.ident_, 0);
    renderC(':');
    ppType(p->u.regradec1_.type_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_RegraDec2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.regradec2_.ident_, 0);
    renderC(':');
    ppType(p->u.regradec2_.type_, 0);
    ppRegraDec(p->u.regradec2_.regradec_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RegraDec!\n");
    exit(1);
  }
}

void ppBlocoVar(BlocoVar p, int _i_)
{
  switch(p->kind)
  {
  case is_BlocoVar1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("VAR");
    ppRegraDecVar(p->u.blocovar1_.regradecvar_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing BlocoVar!\n");
    exit(1);
  }
}

void ppRegraDecVar(RegraDecVar p, int _i_)
{
  switch(p->kind)
  {
  case is_RegraDecVar1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppRegraDec(p->u.regradecvar1_.regradec_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_RegraDecVar2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppRegraDec(p->u.regradecvar2_.regradec_, 0);
    renderC(';');
    ppRegraDecVar(p->u.regradecvar2_.regradecvar_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RegraDecVar!\n");
    exit(1);
  }
}

void ppBlocoType(BlocoType p, int _i_)
{
  switch(p->kind)
  {
  case is_BlocoType1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("TYPE");
    ppRegraType(p->u.blocotype1_.regratype_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing BlocoType!\n");
    exit(1);
  }
}

void ppRegraType(RegraType p, int _i_)
{
  switch(p->kind)
  {
  case is_RegraTypeRegraDecVetor:
    if (_i_ > 0) renderC(_L_PAREN);
    ppRegraDecVetor(p->u.regratyperegradecvetor_.regradecvetor_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_RegraType1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppRegraDecVetor(p->u.regratype1_.regradecvetor_, 0);
    ppRegraType(p->u.regratype1_.regratype_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_RegraTypeRegraDecStruct:
    if (_i_ > 0) renderC(_L_PAREN);
    ppRegraDecStruct(p->u.regratyperegradecstruct_.regradecstruct_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_RegraType2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppRegraDecStruct(p->u.regratype2_.regradecstruct_, 0);
    ppRegraType(p->u.regratype2_.regratype_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RegraType!\n");
    exit(1);
  }
}

void ppRegraDecVetor(RegraDecVetor p, int _i_)
{
  switch(p->kind)
  {
  case is_RegraDecVetor1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.regradecvetor1_.ident_, 0);
    renderC('=');
    renderS("VETOR");
    ppInteger(p->u.regradecvetor1_.integer_, 0);
    renderS("DE");
    ppType(p->u.regradecvetor1_.type_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RegraDecVetor!\n");
    exit(1);
  }
}

void ppRegraDecStruct(RegraDecStruct p, int _i_)
{
  switch(p->kind)
  {
  case is_RegraDecStruct1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.regradecstruct1_.ident_, 0);
    renderC('=');
    renderS("REGISTRO");
    renderS("DE");
    ppRegraDec(p->u.regradecstruct1_.regradec_, 0);
    renderS("END");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_RegraDecStruct2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.regradecstruct2_.ident_, 0);
    renderC('=');
    renderS("REGISTRO");
    renderS("DE");
    ppRegraDec(p->u.regradecstruct2_.regradec_, 0);
    renderS("END");
    ppRegraDecStruct(p->u.regradecstruct2_.regradecstruct_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RegraDecStruct!\n");
    exit(1);
  }
}

void ppBlocoStmt(BlocoStmt p, int _i_)
{
  switch(p->kind)
  {
  case is_BlocoStmt1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("BEGIN");
    ppRegraStmt(p->u.blocostmt1_.regrastmt_, 0);
    renderS("END");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing BlocoStmt!\n");
    exit(1);
  }
}

void ppRegraStmt(RegraStmt p, int _i_)
{
  switch(p->kind)
  {
  case is_RegraStmtStmt:
    if (_i_ > 0) renderC(_L_PAREN);
    ppStmt(p->u.regrastmtstmt_.stmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_RegraStmt1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppStmt(p->u.regrastmt1_.stmt_, 0);
    ppRegraStmt(p->u.regrastmt1_.regrastmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_RegraStmt_:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RegraStmt!\n");
    exit(1);
  }
}

void ppStmt(Stmt p, int _i_)
{
  switch(p->kind)
  {
  case is_Stmt1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppAtribuicao(p->u.stmt1_.atribuicao_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Stmt2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppOpa(p->u.stmt2_.opa_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Stmt3:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIf(p->u.stmt3_.if_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Stmt4:
    if (_i_ > 0) renderC(_L_PAREN);
    ppWhile(p->u.stmt4_.while_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Stmt5:
    if (_i_ > 0) renderC(_L_PAREN);
    ppFor(p->u.stmt5_.for_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Stmt6:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCase(p->u.stmt6_.case_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Stmt!\n");
    exit(1);
  }
}

void ppAtribuicao(Atribuicao p, int _i_)
{
  switch(p->kind)
  {
  case is_Atribuicao1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.atribuicao1_.ident_, 0);
    renderS(":=");
    ppRExpr(p->u.atribuicao1_.rexpr_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_AtribuicaoAtribuicaoVetor:
    if (_i_ > 0) renderC(_L_PAREN);
    ppAtribuicaoVetor(p->u.atribuicaoatribuicaovetor_.atribuicaovetor_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_AtribuicaoAtribuicaoStruct:
    if (_i_ > 0) renderC(_L_PAREN);
    ppAtribuicaoStruct(p->u.atribuicaoatribuicaostruct_.atribuicaostruct_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Atribuicao!\n");
    exit(1);
  }
}

void ppAtribuicaoVetor(AtribuicaoVetor p, int _i_)
{
  switch(p->kind)
  {
  case is_AtribuicaoVetor1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.atribuicaovetor1_.ident_, 0);
    renderC('[');
    ppInteger(p->u.atribuicaovetor1_.integer_, 0);
    renderC(']');
    renderS(":=");
    ppValor(p->u.atribuicaovetor1_.valor_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_AtribuicaoVetor2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.atribuicaovetor2_.ident_1, 0);
    renderC('[');
    ppInteger(p->u.atribuicaovetor2_.integer_, 0);
    renderC(']');
    renderS(":=");
    ppIdent(p->u.atribuicaovetor2_.ident_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing AtribuicaoVetor!\n");
    exit(1);
  }
}

void ppAtribuicaoStruct(AtribuicaoStruct p, int _i_)
{
  switch(p->kind)
  {
  case is_AtribuicaoStruct1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.atribuicaostruct1_.ident_1, 0);
    renderC('.');
    ppIdent(p->u.atribuicaostruct1_.ident_2, 0);
    renderS(":=");
    ppValor(p->u.atribuicaostruct1_.valor_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_AtribuicaoStruct2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.atribuicaostruct2_.ident_1, 0);
    renderC('.');
    ppIdent(p->u.atribuicaostruct2_.ident_2, 0);
    renderS(":=");
    ppIdent(p->u.atribuicaostruct2_.ident_3, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing AtribuicaoStruct!\n");
    exit(1);
  }
}

void ppValor(Valor p, int _i_)
{
  switch(p->kind)
  {
  case is_ValorString:
    if (_i_ > 0) renderC(_L_PAREN);
    ppString(p->u.valorstring_.string_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ValorChar:
    if (_i_ > 0) renderC(_L_PAREN);
    ppChar(p->u.valorchar_.char_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ValorDouble:
    if (_i_ > 0) renderC(_L_PAREN);
    ppDouble(p->u.valordouble_.double_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ValorInteger:
    if (_i_ > 0) renderC(_L_PAREN);
    ppInteger(p->u.valorinteger_.integer_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Valor!\n");
    exit(1);
  }
}

void ppRExpr(RExpr p, int _i_)
{
  switch(p->kind)
  {
  case is_RExprValor:
    if (_i_ > 0) renderC(_L_PAREN);
    ppValor(p->u.rexprvalor_.valor_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_RExprIdent:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.rexprident_.ident_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_RExprOpa:
    if (_i_ > 0) renderC(_L_PAREN);
    ppOpa(p->u.rexpropa_.opa_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RExpr!\n");
    exit(1);
  }
}

void ppOpa(Opa p, int _i_)
{
  switch(p->kind)
  {
  case is_LSom:
    if (_i_ > 0) renderC(_L_PAREN);
    ppOpa(p->u.lsom_.opa_1, 0);
    renderC('+');
    ppOpa(p->u.lsom_.opa_2, 1);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_LSub:
    if (_i_ > 0) renderC(_L_PAREN);
    ppOpa(p->u.lsub_.opa_1, 0);
    renderC('-');
    ppOpa(p->u.lsub_.opa_2, 1);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_LMul:
    if (_i_ > 1) renderC(_L_PAREN);
    ppOpa(p->u.lmul_.opa_1, 1);
    renderC('*');
    ppOpa(p->u.lmul_.opa_2, 2);
    if (_i_ > 1) renderC(_R_PAREN);
    break;

  case is_LDiv:
    if (_i_ > 1) renderC(_L_PAREN);
    ppOpa(p->u.ldiv_.opa_1, 1);
    renderC('/');
    ppOpa(p->u.ldiv_.opa_2, 2);
    if (_i_ > 1) renderC(_R_PAREN);
    break;

  case is_Opa2Integer:
    if (_i_ > 2) renderC(_L_PAREN);
    ppInteger(p->u.opa2integer_.integer_, 0);
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  case is_Opa2Double:
    if (_i_ > 2) renderC(_L_PAREN);
    ppDouble(p->u.opa2double_.double_, 0);
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  case is_Opa2Ident:
    if (_i_ > 2) renderC(_L_PAREN);
    ppIdent(p->u.opa2ident_.ident_, 0);
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Opa!\n");
    exit(1);
  }
}

void ppExpressaoLogica(ExpressaoLogica p, int _i_)
{
  switch(p->kind)
  {
  case is_ExpressaoLogica1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppRExpr(p->u.expressaologica1_.rexpr_1, 0);
    ppOperadoresLogicos(p->u.expressaologica1_.operadoreslogicos_, 0);
    ppRExpr(p->u.expressaologica1_.rexpr_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ExpressaoLogica2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppRExpr(p->u.expressaologica2_.rexpr_1, 0);
    ppOperadoresLogicos(p->u.expressaologica2_.operadoreslogicos_, 0);
    ppRExpr(p->u.expressaologica2_.rexpr_2, 0);
    ppConectivosLogicos(p->u.expressaologica2_.conectivoslogicos_, 0);
    ppExpressaoLogica(p->u.expressaologica2_.expressaologica_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ExpressaoLogica!\n");
    exit(1);
  }
}

void ppIf(If p, int _i_)
{
  switch(p->kind)
  {
  case is_IfIfStmt:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIfStmt(p->u.ififstmt_.ifstmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_If1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIfStmt(p->u.if1_.ifstmt_, 0);
    ppElseStmt(p->u.if1_.elsestmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_If2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIfStmt(p->u.if2_.ifstmt_, 0);
    ppElsIfStmt(p->u.if2_.elsifstmt_, 0);
    ppElseStmt(p->u.if2_.elsestmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_If_:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing If!\n");
    exit(1);
  }
}

void ppIfStmt(IfStmt p, int _i_)
{
  switch(p->kind)
  {
  case is_IfStmt1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("IF");
    ppExpressaoLogica(p->u.ifstmt1_.expressaologica_, 0);
    renderS("THEN");
    ppBlocoStmt(p->u.ifstmt1_.blocostmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing IfStmt!\n");
    exit(1);
  }
}

void ppElseStmt(ElseStmt p, int _i_)
{
  switch(p->kind)
  {
  case is_ElseStmt1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("ELSE");
    ppBlocoStmt(p->u.elsestmt1_.blocostmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ElseStmt!\n");
    exit(1);
  }
}

void ppElsIfStmt(ElsIfStmt p, int _i_)
{
  switch(p->kind)
  {
  case is_ElsIfStmt1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("ELSIF");
    ppExpressaoLogica(p->u.elsifstmt1_.expressaologica_, 0);
    renderS("THEN");
    ppBlocoStmt(p->u.elsifstmt1_.blocostmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ElsIfStmt!\n");
    exit(1);
  }
}

void ppWhile(While p, int _i_)
{
  switch(p->kind)
  {
  case is_While1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("WHILE");
    ppExpressaoLogica(p->u.while1_.expressaologica_, 0);
    renderS("DO");
    ppBlocoStmt(p->u.while1_.blocostmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing While!\n");
    exit(1);
  }
}

void ppFor(For p, int _i_)
{
  switch(p->kind)
  {
  case is_For1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("FOR");
    ppAtribuicao(p->u.for1_.atribuicao_, 0);
    renderS("TO");
    ppRExpr(p->u.for1_.rexpr_, 0);
    renderS("DO");
    ppBlocoStmt(p->u.for1_.blocostmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing For!\n");
    exit(1);
  }
}

void ppCase(Case p, int _i_)
{
  switch(p->kind)
  {
  case is_CaseCaseStmt:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCaseStmt(p->u.casecasestmt_.casestmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Case!\n");
    exit(1);
  }
}

void ppCaseStmt(CaseStmt p, int _i_)
{
  switch(p->kind)
  {
  case is_CaseStmt1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("CASE");
    ppIdent(p->u.casestmt1_.ident_, 0);
    renderS("OF");
    ppBlocoStmt(p->u.casestmt1_.blocostmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CaseStmt2:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("ELSE");
    ppBlocoStmt(p->u.casestmt2_.blocostmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CaseStmt!\n");
    exit(1);
  }
}

void ppType(Type p, int _i_)
{
  switch(p->kind)
  {
  case is_Type_INTEGER:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("INTEGER");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Type_REAL:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("REAL");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Type_CHAR:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("CHAR");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Type_STRING:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("STRING");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Type!\n");
    exit(1);
  }
}

void ppOperadoresLogicos(OperadoresLogicos p, int _i_)
{
  switch(p->kind)
  {
  case is_OperadoresLogicos1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('>');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OperadoresLogicos2:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OperadoresLogicos3:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS(">=");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OperadoresLogicos4:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("<=");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OperadoresLogicos5:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('=');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OperadoresLogicos6:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("<>");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OperadoresLogicos!\n");
    exit(1);
  }
}

void ppConectivosLogicos(ConectivosLogicos p, int _i_)
{
  switch(p->kind)
  {
  case is_ConectivosLogicos_AND:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("AND");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ConectivosLogicos_OR:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("OR");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ConectivosLogicos_NOT:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("NOT");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ConectivosLogicos!\n");
    exit(1);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  char tmp[4];
  sprintf(tmp, "'%c'", c);
  renderS(tmp);
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void shProgr(Progr p)
{
  switch(p->kind)
  {
  case is_Program:
    bufAppendC('(');

    bufAppendS("Program");

    bufAppendC(' ');

    shIdent(p->u.program_.ident_1);
  bufAppendC(' ');
    shBlocoDec(p->u.program_.blocodec_);
  bufAppendC(' ');
    shRegraStmt(p->u.program_.regrastmt_);
  bufAppendC(' ');
    shIdent(p->u.program_.ident_2);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Progr!\n");
    exit(1);
  }
}

void shBlocoDec(BlocoDec p)
{
  switch(p->kind)
  {
  case is_BlocoDec1:
    bufAppendC('(');

    bufAppendS("BlocoDec1");

    bufAppendC(' ');

    shBlocoConstante(p->u.blocodec1_.blococonstante_);
  bufAppendC(' ');
    shBlocoDec(p->u.blocodec1_.blocodec_);

    bufAppendC(')');

    break;
  case is_BlocoDec2:
    bufAppendC('(');

    bufAppendS("BlocoDec2");

    bufAppendC(' ');

    shBlocoVar(p->u.blocodec2_.blocovar_);
  bufAppendC(' ');
    shBlocoDec(p->u.blocodec2_.blocodec_);

    bufAppendC(')');

    break;
  case is_BlocoDec3:
    bufAppendC('(');

    bufAppendS("BlocoDec3");

    bufAppendC(' ');

    shBlocoType(p->u.blocodec3_.blocotype_);
  bufAppendC(' ');
    shBlocoDec(p->u.blocodec3_.blocodec_);

    bufAppendC(')');

    break;
  case is_BlocoDec_:

    bufAppendS("BlocoDec_");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing BlocoDec!\n");
    exit(1);
  }
}

void shBlocoConstante(BlocoConstante p)
{
  switch(p->kind)
  {
  case is_BlocoConstante1:
    bufAppendC('(');

    bufAppendS("BlocoConstante1");

    bufAppendC(' ');

    shRegraConstante(p->u.blococonstante1_.regraconstante_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing BlocoConstante!\n");
    exit(1);
  }
}

void shRegraConstante(RegraConstante p)
{
  switch(p->kind)
  {
  case is_RegraConstante1:
    bufAppendC('(');

    bufAppendS("RegraConstante1");

    bufAppendC(' ');

    shIdent(p->u.regraconstante1_.ident_);
  bufAppendC(' ');
    shType(p->u.regraconstante1_.type_);
  bufAppendC(' ');
    shValor(p->u.regraconstante1_.valor_);

    bufAppendC(')');

    break;
  case is_RegraConstante2:
    bufAppendC('(');

    bufAppendS("RegraConstante2");

    bufAppendC(' ');

    shIdent(p->u.regraconstante2_.ident_);
  bufAppendC(' ');
    shType(p->u.regraconstante2_.type_);
  bufAppendC(' ');
    shValor(p->u.regraconstante2_.valor_);
  bufAppendC(' ');
    shRegraConstante(p->u.regraconstante2_.regraconstante_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing RegraConstante!\n");
    exit(1);
  }
}

void shRegraDec(RegraDec p)
{
  switch(p->kind)
  {
  case is_RegraDec1:
    bufAppendC('(');

    bufAppendS("RegraDec1");

    bufAppendC(' ');

    shIdent(p->u.regradec1_.ident_);
  bufAppendC(' ');
    shType(p->u.regradec1_.type_);

    bufAppendC(')');

    break;
  case is_RegraDec2:
    bufAppendC('(');

    bufAppendS("RegraDec2");

    bufAppendC(' ');

    shIdent(p->u.regradec2_.ident_);
  bufAppendC(' ');
    shType(p->u.regradec2_.type_);
  bufAppendC(' ');
    shRegraDec(p->u.regradec2_.regradec_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing RegraDec!\n");
    exit(1);
  }
}

void shBlocoVar(BlocoVar p)
{
  switch(p->kind)
  {
  case is_BlocoVar1:
    bufAppendC('(');

    bufAppendS("BlocoVar1");

    bufAppendC(' ');

    shRegraDecVar(p->u.blocovar1_.regradecvar_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing BlocoVar!\n");
    exit(1);
  }
}

void shRegraDecVar(RegraDecVar p)
{
  switch(p->kind)
  {
  case is_RegraDecVar1:
    bufAppendC('(');

    bufAppendS("RegraDecVar1");

    bufAppendC(' ');

    shRegraDec(p->u.regradecvar1_.regradec_);

    bufAppendC(')');

    break;
  case is_RegraDecVar2:
    bufAppendC('(');

    bufAppendS("RegraDecVar2");

    bufAppendC(' ');

    shRegraDec(p->u.regradecvar2_.regradec_);
  bufAppendC(' ');
    shRegraDecVar(p->u.regradecvar2_.regradecvar_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing RegraDecVar!\n");
    exit(1);
  }
}

void shBlocoType(BlocoType p)
{
  switch(p->kind)
  {
  case is_BlocoType1:
    bufAppendC('(');

    bufAppendS("BlocoType1");

    bufAppendC(' ');

    shRegraType(p->u.blocotype1_.regratype_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing BlocoType!\n");
    exit(1);
  }
}

void shRegraType(RegraType p)
{
  switch(p->kind)
  {
  case is_RegraTypeRegraDecVetor:
    bufAppendC('(');

    bufAppendS("RegraTypeRegraDecVetor");

    bufAppendC(' ');

    shRegraDecVetor(p->u.regratyperegradecvetor_.regradecvetor_);

    bufAppendC(')');

    break;
  case is_RegraType1:
    bufAppendC('(');

    bufAppendS("RegraType1");

    bufAppendC(' ');

    shRegraDecVetor(p->u.regratype1_.regradecvetor_);
  bufAppendC(' ');
    shRegraType(p->u.regratype1_.regratype_);

    bufAppendC(')');

    break;
  case is_RegraTypeRegraDecStruct:
    bufAppendC('(');

    bufAppendS("RegraTypeRegraDecStruct");

    bufAppendC(' ');

    shRegraDecStruct(p->u.regratyperegradecstruct_.regradecstruct_);

    bufAppendC(')');

    break;
  case is_RegraType2:
    bufAppendC('(');

    bufAppendS("RegraType2");

    bufAppendC(' ');

    shRegraDecStruct(p->u.regratype2_.regradecstruct_);
  bufAppendC(' ');
    shRegraType(p->u.regratype2_.regratype_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing RegraType!\n");
    exit(1);
  }
}

void shRegraDecVetor(RegraDecVetor p)
{
  switch(p->kind)
  {
  case is_RegraDecVetor1:
    bufAppendC('(');

    bufAppendS("RegraDecVetor1");

    bufAppendC(' ');

    shIdent(p->u.regradecvetor1_.ident_);
  bufAppendC(' ');
    shInteger(p->u.regradecvetor1_.integer_);
  bufAppendC(' ');
    shType(p->u.regradecvetor1_.type_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing RegraDecVetor!\n");
    exit(1);
  }
}

void shRegraDecStruct(RegraDecStruct p)
{
  switch(p->kind)
  {
  case is_RegraDecStruct1:
    bufAppendC('(');

    bufAppendS("RegraDecStruct1");

    bufAppendC(' ');

    shIdent(p->u.regradecstruct1_.ident_);
  bufAppendC(' ');
    shRegraDec(p->u.regradecstruct1_.regradec_);

    bufAppendC(')');

    break;
  case is_RegraDecStruct2:
    bufAppendC('(');

    bufAppendS("RegraDecStruct2");

    bufAppendC(' ');

    shIdent(p->u.regradecstruct2_.ident_);
  bufAppendC(' ');
    shRegraDec(p->u.regradecstruct2_.regradec_);
  bufAppendC(' ');
    shRegraDecStruct(p->u.regradecstruct2_.regradecstruct_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing RegraDecStruct!\n");
    exit(1);
  }
}

void shBlocoStmt(BlocoStmt p)
{
  switch(p->kind)
  {
  case is_BlocoStmt1:
    bufAppendC('(');

    bufAppendS("BlocoStmt1");

    bufAppendC(' ');

    shRegraStmt(p->u.blocostmt1_.regrastmt_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing BlocoStmt!\n");
    exit(1);
  }
}

void shRegraStmt(RegraStmt p)
{
  switch(p->kind)
  {
  case is_RegraStmtStmt:
    bufAppendC('(');

    bufAppendS("RegraStmtStmt");

    bufAppendC(' ');

    shStmt(p->u.regrastmtstmt_.stmt_);

    bufAppendC(')');

    break;
  case is_RegraStmt1:
    bufAppendC('(');

    bufAppendS("RegraStmt1");

    bufAppendC(' ');

    shStmt(p->u.regrastmt1_.stmt_);
  bufAppendC(' ');
    shRegraStmt(p->u.regrastmt1_.regrastmt_);

    bufAppendC(')');

    break;
  case is_RegraStmt_:

    bufAppendS("RegraStmt_");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing RegraStmt!\n");
    exit(1);
  }
}

void shStmt(Stmt p)
{
  switch(p->kind)
  {
  case is_Stmt1:
    bufAppendC('(');

    bufAppendS("Stmt1");

    bufAppendC(' ');

    shAtribuicao(p->u.stmt1_.atribuicao_);

    bufAppendC(')');

    break;
  case is_Stmt2:
    bufAppendC('(');

    bufAppendS("Stmt2");

    bufAppendC(' ');

    shOpa(p->u.stmt2_.opa_);

    bufAppendC(')');

    break;
  case is_Stmt3:
    bufAppendC('(');

    bufAppendS("Stmt3");

    bufAppendC(' ');

    shIf(p->u.stmt3_.if_);

    bufAppendC(')');

    break;
  case is_Stmt4:
    bufAppendC('(');

    bufAppendS("Stmt4");

    bufAppendC(' ');

    shWhile(p->u.stmt4_.while_);

    bufAppendC(')');

    break;
  case is_Stmt5:
    bufAppendC('(');

    bufAppendS("Stmt5");

    bufAppendC(' ');

    shFor(p->u.stmt5_.for_);

    bufAppendC(')');

    break;
  case is_Stmt6:
    bufAppendC('(');

    bufAppendS("Stmt6");

    bufAppendC(' ');

    shCase(p->u.stmt6_.case_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Stmt!\n");
    exit(1);
  }
}

void shAtribuicao(Atribuicao p)
{
  switch(p->kind)
  {
  case is_Atribuicao1:
    bufAppendC('(');

    bufAppendS("Atribuicao1");

    bufAppendC(' ');

    shIdent(p->u.atribuicao1_.ident_);
  bufAppendC(' ');
    shRExpr(p->u.atribuicao1_.rexpr_);

    bufAppendC(')');

    break;
  case is_AtribuicaoAtribuicaoVetor:
    bufAppendC('(');

    bufAppendS("AtribuicaoAtribuicaoVetor");

    bufAppendC(' ');

    shAtribuicaoVetor(p->u.atribuicaoatribuicaovetor_.atribuicaovetor_);

    bufAppendC(')');

    break;
  case is_AtribuicaoAtribuicaoStruct:
    bufAppendC('(');

    bufAppendS("AtribuicaoAtribuicaoStruct");

    bufAppendC(' ');

    shAtribuicaoStruct(p->u.atribuicaoatribuicaostruct_.atribuicaostruct_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Atribuicao!\n");
    exit(1);
  }
}

void shAtribuicaoVetor(AtribuicaoVetor p)
{
  switch(p->kind)
  {
  case is_AtribuicaoVetor1:
    bufAppendC('(');

    bufAppendS("AtribuicaoVetor1");

    bufAppendC(' ');

    shIdent(p->u.atribuicaovetor1_.ident_);
  bufAppendC(' ');
    shInteger(p->u.atribuicaovetor1_.integer_);
  bufAppendC(' ');
    shValor(p->u.atribuicaovetor1_.valor_);

    bufAppendC(')');

    break;
  case is_AtribuicaoVetor2:
    bufAppendC('(');

    bufAppendS("AtribuicaoVetor2");

    bufAppendC(' ');

    shIdent(p->u.atribuicaovetor2_.ident_1);
  bufAppendC(' ');
    shInteger(p->u.atribuicaovetor2_.integer_);
  bufAppendC(' ');
    shIdent(p->u.atribuicaovetor2_.ident_2);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing AtribuicaoVetor!\n");
    exit(1);
  }
}

void shAtribuicaoStruct(AtribuicaoStruct p)
{
  switch(p->kind)
  {
  case is_AtribuicaoStruct1:
    bufAppendC('(');

    bufAppendS("AtribuicaoStruct1");

    bufAppendC(' ');

    shIdent(p->u.atribuicaostruct1_.ident_1);
  bufAppendC(' ');
    shIdent(p->u.atribuicaostruct1_.ident_2);
  bufAppendC(' ');
    shValor(p->u.atribuicaostruct1_.valor_);

    bufAppendC(')');

    break;
  case is_AtribuicaoStruct2:
    bufAppendC('(');

    bufAppendS("AtribuicaoStruct2");

    bufAppendC(' ');

    shIdent(p->u.atribuicaostruct2_.ident_1);
  bufAppendC(' ');
    shIdent(p->u.atribuicaostruct2_.ident_2);
  bufAppendC(' ');
    shIdent(p->u.atribuicaostruct2_.ident_3);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing AtribuicaoStruct!\n");
    exit(1);
  }
}

void shValor(Valor p)
{
  switch(p->kind)
  {
  case is_ValorString:
    bufAppendC('(');

    bufAppendS("ValorString");

    bufAppendC(' ');

    shString(p->u.valorstring_.string_);

    bufAppendC(')');

    break;
  case is_ValorChar:
    bufAppendC('(');

    bufAppendS("ValorChar");

    bufAppendC(' ');

    shChar(p->u.valorchar_.char_);

    bufAppendC(')');

    break;
  case is_ValorDouble:
    bufAppendC('(');

    bufAppendS("ValorDouble");

    bufAppendC(' ');

    shDouble(p->u.valordouble_.double_);

    bufAppendC(')');

    break;
  case is_ValorInteger:
    bufAppendC('(');

    bufAppendS("ValorInteger");

    bufAppendC(' ');

    shInteger(p->u.valorinteger_.integer_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Valor!\n");
    exit(1);
  }
}

void shRExpr(RExpr p)
{
  switch(p->kind)
  {
  case is_RExprValor:
    bufAppendC('(');

    bufAppendS("RExprValor");

    bufAppendC(' ');

    shValor(p->u.rexprvalor_.valor_);

    bufAppendC(')');

    break;
  case is_RExprIdent:
    bufAppendC('(');

    bufAppendS("RExprIdent");

    bufAppendC(' ');

    shIdent(p->u.rexprident_.ident_);

    bufAppendC(')');

    break;
  case is_RExprOpa:
    bufAppendC('(');

    bufAppendS("RExprOpa");

    bufAppendC(' ');

    shOpa(p->u.rexpropa_.opa_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing RExpr!\n");
    exit(1);
  }
}

void shOpa(Opa p)
{
  switch(p->kind)
  {
  case is_LSom:
    bufAppendC('(');

    bufAppendS("LSom");

    bufAppendC(' ');

    shOpa(p->u.lsom_.opa_1);
  bufAppendC(' ');
    shOpa(p->u.lsom_.opa_2);

    bufAppendC(')');

    break;
  case is_LSub:
    bufAppendC('(');

    bufAppendS("LSub");

    bufAppendC(' ');

    shOpa(p->u.lsub_.opa_1);
  bufAppendC(' ');
    shOpa(p->u.lsub_.opa_2);

    bufAppendC(')');

    break;
  case is_LMul:
    bufAppendC('(');

    bufAppendS("LMul");

    bufAppendC(' ');

    shOpa(p->u.lmul_.opa_1);
  bufAppendC(' ');
    shOpa(p->u.lmul_.opa_2);

    bufAppendC(')');

    break;
  case is_LDiv:
    bufAppendC('(');

    bufAppendS("LDiv");

    bufAppendC(' ');

    shOpa(p->u.ldiv_.opa_1);
  bufAppendC(' ');
    shOpa(p->u.ldiv_.opa_2);

    bufAppendC(')');

    break;
  case is_Opa2Integer:
    bufAppendC('(');

    bufAppendS("Opa2Integer");

    bufAppendC(' ');

    shInteger(p->u.opa2integer_.integer_);

    bufAppendC(')');

    break;
  case is_Opa2Double:
    bufAppendC('(');

    bufAppendS("Opa2Double");

    bufAppendC(' ');

    shDouble(p->u.opa2double_.double_);

    bufAppendC(')');

    break;
  case is_Opa2Ident:
    bufAppendC('(');

    bufAppendS("Opa2Ident");

    bufAppendC(' ');

    shIdent(p->u.opa2ident_.ident_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Opa!\n");
    exit(1);
  }
}

void shExpressaoLogica(ExpressaoLogica p)
{
  switch(p->kind)
  {
  case is_ExpressaoLogica1:
    bufAppendC('(');

    bufAppendS("ExpressaoLogica1");

    bufAppendC(' ');

    shRExpr(p->u.expressaologica1_.rexpr_1);
  bufAppendC(' ');
    shOperadoresLogicos(p->u.expressaologica1_.operadoreslogicos_);
  bufAppendC(' ');
    shRExpr(p->u.expressaologica1_.rexpr_2);

    bufAppendC(')');

    break;
  case is_ExpressaoLogica2:
    bufAppendC('(');

    bufAppendS("ExpressaoLogica2");

    bufAppendC(' ');

    shRExpr(p->u.expressaologica2_.rexpr_1);
  bufAppendC(' ');
    shOperadoresLogicos(p->u.expressaologica2_.operadoreslogicos_);
  bufAppendC(' ');
    shRExpr(p->u.expressaologica2_.rexpr_2);
  bufAppendC(' ');
    shConectivosLogicos(p->u.expressaologica2_.conectivoslogicos_);
  bufAppendC(' ');
    shExpressaoLogica(p->u.expressaologica2_.expressaologica_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ExpressaoLogica!\n");
    exit(1);
  }
}

void shIf(If p)
{
  switch(p->kind)
  {
  case is_IfIfStmt:
    bufAppendC('(');

    bufAppendS("IfIfStmt");

    bufAppendC(' ');

    shIfStmt(p->u.ififstmt_.ifstmt_);

    bufAppendC(')');

    break;
  case is_If1:
    bufAppendC('(');

    bufAppendS("If1");

    bufAppendC(' ');

    shIfStmt(p->u.if1_.ifstmt_);
  bufAppendC(' ');
    shElseStmt(p->u.if1_.elsestmt_);

    bufAppendC(')');

    break;
  case is_If2:
    bufAppendC('(');

    bufAppendS("If2");

    bufAppendC(' ');

    shIfStmt(p->u.if2_.ifstmt_);
  bufAppendC(' ');
    shElsIfStmt(p->u.if2_.elsifstmt_);
  bufAppendC(' ');
    shElseStmt(p->u.if2_.elsestmt_);

    bufAppendC(')');

    break;
  case is_If_:

    bufAppendS("If_");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing If!\n");
    exit(1);
  }
}

void shIfStmt(IfStmt p)
{
  switch(p->kind)
  {
  case is_IfStmt1:
    bufAppendC('(');

    bufAppendS("IfStmt1");

    bufAppendC(' ');

    shExpressaoLogica(p->u.ifstmt1_.expressaologica_);
  bufAppendC(' ');
    shBlocoStmt(p->u.ifstmt1_.blocostmt_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing IfStmt!\n");
    exit(1);
  }
}

void shElseStmt(ElseStmt p)
{
  switch(p->kind)
  {
  case is_ElseStmt1:
    bufAppendC('(');

    bufAppendS("ElseStmt1");

    bufAppendC(' ');

    shBlocoStmt(p->u.elsestmt1_.blocostmt_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ElseStmt!\n");
    exit(1);
  }
}

void shElsIfStmt(ElsIfStmt p)
{
  switch(p->kind)
  {
  case is_ElsIfStmt1:
    bufAppendC('(');

    bufAppendS("ElsIfStmt1");

    bufAppendC(' ');

    shExpressaoLogica(p->u.elsifstmt1_.expressaologica_);
  bufAppendC(' ');
    shBlocoStmt(p->u.elsifstmt1_.blocostmt_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ElsIfStmt!\n");
    exit(1);
  }
}

void shWhile(While p)
{
  switch(p->kind)
  {
  case is_While1:
    bufAppendC('(');

    bufAppendS("While1");

    bufAppendC(' ');

    shExpressaoLogica(p->u.while1_.expressaologica_);
  bufAppendC(' ');
    shBlocoStmt(p->u.while1_.blocostmt_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing While!\n");
    exit(1);
  }
}

void shFor(For p)
{
  switch(p->kind)
  {
  case is_For1:
    bufAppendC('(');

    bufAppendS("For1");

    bufAppendC(' ');

    shAtribuicao(p->u.for1_.atribuicao_);
  bufAppendC(' ');
    shRExpr(p->u.for1_.rexpr_);
  bufAppendC(' ');
    shBlocoStmt(p->u.for1_.blocostmt_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing For!\n");
    exit(1);
  }
}

void shCase(Case p)
{
  switch(p->kind)
  {
  case is_CaseCaseStmt:
    bufAppendC('(');

    bufAppendS("CaseCaseStmt");

    bufAppendC(' ');

    shCaseStmt(p->u.casecasestmt_.casestmt_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Case!\n");
    exit(1);
  }
}

void shCaseStmt(CaseStmt p)
{
  switch(p->kind)
  {
  case is_CaseStmt1:
    bufAppendC('(');

    bufAppendS("CaseStmt1");

    bufAppendC(' ');

    shIdent(p->u.casestmt1_.ident_);
  bufAppendC(' ');
    shBlocoStmt(p->u.casestmt1_.blocostmt_);

    bufAppendC(')');

    break;
  case is_CaseStmt2:
    bufAppendC('(');

    bufAppendS("CaseStmt2");

    bufAppendC(' ');

    shBlocoStmt(p->u.casestmt2_.blocostmt_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing CaseStmt!\n");
    exit(1);
  }
}

void shType(Type p)
{
  switch(p->kind)
  {
  case is_Type_INTEGER:

    bufAppendS("Type_INTEGER");




    break;
  case is_Type_REAL:

    bufAppendS("Type_REAL");




    break;
  case is_Type_CHAR:

    bufAppendS("Type_CHAR");




    break;
  case is_Type_STRING:

    bufAppendS("Type_STRING");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Type!\n");
    exit(1);
  }
}

void shOperadoresLogicos(OperadoresLogicos p)
{
  switch(p->kind)
  {
  case is_OperadoresLogicos1:

    bufAppendS("OperadoresLogicos1");




    break;
  case is_OperadoresLogicos2:

    bufAppendS("OperadoresLogicos2");




    break;
  case is_OperadoresLogicos3:

    bufAppendS("OperadoresLogicos3");




    break;
  case is_OperadoresLogicos4:

    bufAppendS("OperadoresLogicos4");




    break;
  case is_OperadoresLogicos5:

    bufAppendS("OperadoresLogicos5");




    break;
  case is_OperadoresLogicos6:

    bufAppendS("OperadoresLogicos6");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing OperadoresLogicos!\n");
    exit(1);
  }
}

void shConectivosLogicos(ConectivosLogicos p)
{
  switch(p->kind)
  {
  case is_ConectivosLogicos_AND:

    bufAppendS("ConectivosLogicos_AND");




    break;
  case is_ConectivosLogicos_OR:

    bufAppendS("ConectivosLogicos_OR");




    break;
  case is_ConectivosLogicos_NOT:

    bufAppendS("ConectivosLogicos_NOT");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ConectivosLogicos!\n");
    exit(1);
  }
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufAppendC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

