/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Traversal Skeleton. ***/
/* This traverses the abstract syntax tree.
   To use, copy Skeleton.h and Skeleton.c to
   new files. */

#include <stdlib.h>
#include <stdio.h>

#include "Skeleton.h"

void visitProgr(Progr p)
{
  switch(p->kind)
  {
  case is_Program:
    /* Code for Program Goes Here */
    visitIdent(p->u.program_.ident_1);
    visitBlocoDec(p->u.program_.blocodec_);
    visitRegraStmt(p->u.program_.regrastmt_);
    visitIdent(p->u.program_.ident_2);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Progr!\n");
    exit(1);
  }
}

void visitBlocoDec(BlocoDec p)
{
  switch(p->kind)
  {
  case is_BlocoDec1:
    /* Code for BlocoDec1 Goes Here */
    visitBlocoConstante(p->u.blocodec1_.blococonstante_);
    visitBlocoDec(p->u.blocodec1_.blocodec_);
    break;
  case is_BlocoDec2:
    /* Code for BlocoDec2 Goes Here */
    visitBlocoVar(p->u.blocodec2_.blocovar_);
    visitBlocoDec(p->u.blocodec2_.blocodec_);
    break;
  case is_BlocoDec3:
    /* Code for BlocoDec3 Goes Here */
    visitBlocoType(p->u.blocodec3_.blocotype_);
    visitBlocoDec(p->u.blocodec3_.blocodec_);
    break;
  case is_BlocoDec_:
    /* Code for BlocoDec_ Goes Here */
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing BlocoDec!\n");
    exit(1);
  }
}

void visitBlocoConstante(BlocoConstante p)
{
  switch(p->kind)
  {
  case is_BlocoConstante1:
    /* Code for BlocoConstante1 Goes Here */
    visitRegraConstante(p->u.blococonstante1_.regraconstante_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing BlocoConstante!\n");
    exit(1);
  }
}

void visitRegraConstante(RegraConstante p)
{
  switch(p->kind)
  {
  case is_RegraConstante1:
    /* Code for RegraConstante1 Goes Here */
    visitIdent(p->u.regraconstante1_.ident_);
    visitType(p->u.regraconstante1_.type_);
    visitValor(p->u.regraconstante1_.valor_);
    break;
  case is_RegraConstante2:
    /* Code for RegraConstante2 Goes Here */
    visitIdent(p->u.regraconstante2_.ident_);
    visitType(p->u.regraconstante2_.type_);
    visitValor(p->u.regraconstante2_.valor_);
    visitRegraConstante(p->u.regraconstante2_.regraconstante_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RegraConstante!\n");
    exit(1);
  }
}

void visitRegraDec(RegraDec p)
{
  switch(p->kind)
  {
  case is_RegraDec1:
    /* Code for RegraDec1 Goes Here */
    visitIdent(p->u.regradec1_.ident_);
    visitType(p->u.regradec1_.type_);
    break;
  case is_RegraDec2:
    /* Code for RegraDec2 Goes Here */
    visitIdent(p->u.regradec2_.ident_);
    visitType(p->u.regradec2_.type_);
    visitRegraDec(p->u.regradec2_.regradec_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RegraDec!\n");
    exit(1);
  }
}

void visitBlocoVar(BlocoVar p)
{
  switch(p->kind)
  {
  case is_BlocoVar1:
    /* Code for BlocoVar1 Goes Here */
    visitRegraDecVar(p->u.blocovar1_.regradecvar_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing BlocoVar!\n");
    exit(1);
  }
}

void visitRegraDecVar(RegraDecVar p)
{
  switch(p->kind)
  {
  case is_RegraDecVar1:
    /* Code for RegraDecVar1 Goes Here */
    visitRegraDec(p->u.regradecvar1_.regradec_);
    break;
  case is_RegraDecVar2:
    /* Code for RegraDecVar2 Goes Here */
    visitRegraDec(p->u.regradecvar2_.regradec_);
    visitRegraDecVar(p->u.regradecvar2_.regradecvar_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RegraDecVar!\n");
    exit(1);
  }
}

void visitBlocoType(BlocoType p)
{
  switch(p->kind)
  {
  case is_BlocoType1:
    /* Code for BlocoType1 Goes Here */
    visitRegraType(p->u.blocotype1_.regratype_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing BlocoType!\n");
    exit(1);
  }
}

void visitRegraType(RegraType p)
{
  switch(p->kind)
  {
  case is_RegraTypeRegraDecVetor:
    /* Code for RegraTypeRegraDecVetor Goes Here */
    visitRegraDecVetor(p->u.regratyperegradecvetor_.regradecvetor_);
    break;
  case is_RegraType1:
    /* Code for RegraType1 Goes Here */
    visitRegraDecVetor(p->u.regratype1_.regradecvetor_);
    visitRegraType(p->u.regratype1_.regratype_);
    break;
  case is_RegraTypeRegraDecStruct:
    /* Code for RegraTypeRegraDecStruct Goes Here */
    visitRegraDecStruct(p->u.regratyperegradecstruct_.regradecstruct_);
    break;
  case is_RegraType2:
    /* Code for RegraType2 Goes Here */
    visitRegraDecStruct(p->u.regratype2_.regradecstruct_);
    visitRegraType(p->u.regratype2_.regratype_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RegraType!\n");
    exit(1);
  }
}

void visitRegraDecVetor(RegraDecVetor p)
{
  switch(p->kind)
  {
  case is_RegraDecVetor1:
    /* Code for RegraDecVetor1 Goes Here */
    visitIdent(p->u.regradecvetor1_.ident_);
    visitInteger(p->u.regradecvetor1_.integer_);
    visitType(p->u.regradecvetor1_.type_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RegraDecVetor!\n");
    exit(1);
  }
}

void visitRegraDecStruct(RegraDecStruct p)
{
  switch(p->kind)
  {
  case is_RegraDecStruct1:
    /* Code for RegraDecStruct1 Goes Here */
    visitIdent(p->u.regradecstruct1_.ident_);
    visitRegraDec(p->u.regradecstruct1_.regradec_);
    break;
  case is_RegraDecStruct2:
    /* Code for RegraDecStruct2 Goes Here */
    visitIdent(p->u.regradecstruct2_.ident_);
    visitRegraDec(p->u.regradecstruct2_.regradec_);
    visitRegraDecStruct(p->u.regradecstruct2_.regradecstruct_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RegraDecStruct!\n");
    exit(1);
  }
}

void visitBlocoStmt(BlocoStmt p)
{
  switch(p->kind)
  {
  case is_BlocoStmt1:
    /* Code for BlocoStmt1 Goes Here */
    visitRegraStmt(p->u.blocostmt1_.regrastmt_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing BlocoStmt!\n");
    exit(1);
  }
}

void visitRegraStmt(RegraStmt p)
{
  switch(p->kind)
  {
  case is_RegraStmtStmt:
    /* Code for RegraStmtStmt Goes Here */
    visitStmt(p->u.regrastmtstmt_.stmt_);
    break;
  case is_RegraStmt1:
    /* Code for RegraStmt1 Goes Here */
    visitStmt(p->u.regrastmt1_.stmt_);
    visitRegraStmt(p->u.regrastmt1_.regrastmt_);
    break;
  case is_RegraStmt_:
    /* Code for RegraStmt_ Goes Here */
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RegraStmt!\n");
    exit(1);
  }
}

void visitStmt(Stmt p)
{
  switch(p->kind)
  {
  case is_Stmt1:
    /* Code for Stmt1 Goes Here */
    visitAtribuicao(p->u.stmt1_.atribuicao_);
    break;
  case is_Stmt2:
    /* Code for Stmt2 Goes Here */
    visitOpa(p->u.stmt2_.opa_);
    break;
  case is_Stmt3:
    /* Code for Stmt3 Goes Here */
    visitIf(p->u.stmt3_.if_);
    break;
  case is_Stmt4:
    /* Code for Stmt4 Goes Here */
    visitWhile(p->u.stmt4_.while_);
    break;
  case is_Stmt5:
    /* Code for Stmt5 Goes Here */
    visitFor(p->u.stmt5_.for_);
    break;
  case is_Stmt6:
    /* Code for Stmt6 Goes Here */
    visitCase(p->u.stmt6_.case_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Stmt!\n");
    exit(1);
  }
}

void visitAtribuicao(Atribuicao p)
{
  switch(p->kind)
  {
  case is_Atribuicao1:
    /* Code for Atribuicao1 Goes Here */
    visitIdent(p->u.atribuicao1_.ident_);
    visitRExpr(p->u.atribuicao1_.rexpr_);
    break;
  case is_AtribuicaoAtribuicaoVetor:
    /* Code for AtribuicaoAtribuicaoVetor Goes Here */
    visitAtribuicaoVetor(p->u.atribuicaoatribuicaovetor_.atribuicaovetor_);
    break;
  case is_AtribuicaoAtribuicaoStruct:
    /* Code for AtribuicaoAtribuicaoStruct Goes Here */
    visitAtribuicaoStruct(p->u.atribuicaoatribuicaostruct_.atribuicaostruct_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Atribuicao!\n");
    exit(1);
  }
}

void visitAtribuicaoVetor(AtribuicaoVetor p)
{
  switch(p->kind)
  {
  case is_AtribuicaoVetor1:
    /* Code for AtribuicaoVetor1 Goes Here */
    visitIdent(p->u.atribuicaovetor1_.ident_);
    visitInteger(p->u.atribuicaovetor1_.integer_);
    visitValor(p->u.atribuicaovetor1_.valor_);
    break;
  case is_AtribuicaoVetor2:
    /* Code for AtribuicaoVetor2 Goes Here */
    visitIdent(p->u.atribuicaovetor2_.ident_1);
    visitInteger(p->u.atribuicaovetor2_.integer_);
    visitIdent(p->u.atribuicaovetor2_.ident_2);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing AtribuicaoVetor!\n");
    exit(1);
  }
}

void visitAtribuicaoStruct(AtribuicaoStruct p)
{
  switch(p->kind)
  {
  case is_AtribuicaoStruct1:
    /* Code for AtribuicaoStruct1 Goes Here */
    visitIdent(p->u.atribuicaostruct1_.ident_1);
    visitIdent(p->u.atribuicaostruct1_.ident_2);
    visitValor(p->u.atribuicaostruct1_.valor_);
    break;
  case is_AtribuicaoStruct2:
    /* Code for AtribuicaoStruct2 Goes Here */
    visitIdent(p->u.atribuicaostruct2_.ident_1);
    visitIdent(p->u.atribuicaostruct2_.ident_2);
    visitIdent(p->u.atribuicaostruct2_.ident_3);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing AtribuicaoStruct!\n");
    exit(1);
  }
}

void visitValor(Valor p)
{
  switch(p->kind)
  {
  case is_ValorString:
    /* Code for ValorString Goes Here */
    visitString(p->u.valorstring_.string_);
    break;
  case is_ValorChar:
    /* Code for ValorChar Goes Here */
    visitChar(p->u.valorchar_.char_);
    break;
  case is_ValorDouble:
    /* Code for ValorDouble Goes Here */
    visitDouble(p->u.valordouble_.double_);
    break;
  case is_ValorInteger:
    /* Code for ValorInteger Goes Here */
    visitInteger(p->u.valorinteger_.integer_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Valor!\n");
    exit(1);
  }
}

void visitRExpr(RExpr p)
{
  switch(p->kind)
  {
  case is_RExprValor:
    /* Code for RExprValor Goes Here */
    visitValor(p->u.rexprvalor_.valor_);
    break;
  case is_RExprIdent:
    /* Code for RExprIdent Goes Here */
    visitIdent(p->u.rexprident_.ident_);
    break;
  case is_RExprOpa:
    /* Code for RExprOpa Goes Here */
    visitOpa(p->u.rexpropa_.opa_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RExpr!\n");
    exit(1);
  }
}

void visitOpa(Opa p)
{
  switch(p->kind)
  {
  case is_LSom:
    /* Code for LSom Goes Here */
    visitOpa(p->u.lsom_.opa_1);
    visitOpa(p->u.lsom_.opa_2);
    break;
  case is_LSub:
    /* Code for LSub Goes Here */
    visitOpa(p->u.lsub_.opa_1);
    visitOpa(p->u.lsub_.opa_2);
    break;
  case is_LMul:
    /* Code for LMul Goes Here */
    visitOpa(p->u.lmul_.opa_1);
    visitOpa(p->u.lmul_.opa_2);
    break;
  case is_LDiv:
    /* Code for LDiv Goes Here */
    visitOpa(p->u.ldiv_.opa_1);
    visitOpa(p->u.ldiv_.opa_2);
    break;
  case is_Opa2Integer:
    /* Code for Opa2Integer Goes Here */
    visitInteger(p->u.opa2integer_.integer_);
    break;
  case is_Opa2Double:
    /* Code for Opa2Double Goes Here */
    visitDouble(p->u.opa2double_.double_);
    break;
  case is_Opa2Ident:
    /* Code for Opa2Ident Goes Here */
    visitIdent(p->u.opa2ident_.ident_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Opa!\n");
    exit(1);
  }
}

void visitExpressaoLogica(ExpressaoLogica p)
{
  switch(p->kind)
  {
  case is_ExpressaoLogica1:
    /* Code for ExpressaoLogica1 Goes Here */
    visitRExpr(p->u.expressaologica1_.rexpr_1);
    visitOperadoresLogicos(p->u.expressaologica1_.operadoreslogicos_);
    visitRExpr(p->u.expressaologica1_.rexpr_2);
    break;
  case is_ExpressaoLogica2:
    /* Code for ExpressaoLogica2 Goes Here */
    visitRExpr(p->u.expressaologica2_.rexpr_1);
    visitOperadoresLogicos(p->u.expressaologica2_.operadoreslogicos_);
    visitRExpr(p->u.expressaologica2_.rexpr_2);
    visitConectivosLogicos(p->u.expressaologica2_.conectivoslogicos_);
    visitExpressaoLogica(p->u.expressaologica2_.expressaologica_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ExpressaoLogica!\n");
    exit(1);
  }
}

void visitIf(If p)
{
  switch(p->kind)
  {
  case is_IfIfStmt:
    /* Code for IfIfStmt Goes Here */
    visitIfStmt(p->u.ififstmt_.ifstmt_);
    break;
  case is_If1:
    /* Code for If1 Goes Here */
    visitIfStmt(p->u.if1_.ifstmt_);
    visitElseStmt(p->u.if1_.elsestmt_);
    break;
  case is_If2:
    /* Code for If2 Goes Here */
    visitIfStmt(p->u.if2_.ifstmt_);
    visitElsIfStmt(p->u.if2_.elsifstmt_);
    visitElseStmt(p->u.if2_.elsestmt_);
    break;
  case is_If_:
    /* Code for If_ Goes Here */
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing If!\n");
    exit(1);
  }
}

void visitIfStmt(IfStmt p)
{
  switch(p->kind)
  {
  case is_IfStmt1:
    /* Code for IfStmt1 Goes Here */
    visitExpressaoLogica(p->u.ifstmt1_.expressaologica_);
    visitBlocoStmt(p->u.ifstmt1_.blocostmt_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing IfStmt!\n");
    exit(1);
  }
}

void visitElseStmt(ElseStmt p)
{
  switch(p->kind)
  {
  case is_ElseStmt1:
    /* Code for ElseStmt1 Goes Here */
    visitBlocoStmt(p->u.elsestmt1_.blocostmt_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ElseStmt!\n");
    exit(1);
  }
}

void visitElsIfStmt(ElsIfStmt p)
{
  switch(p->kind)
  {
  case is_ElsIfStmt1:
    /* Code for ElsIfStmt1 Goes Here */
    visitExpressaoLogica(p->u.elsifstmt1_.expressaologica_);
    visitBlocoStmt(p->u.elsifstmt1_.blocostmt_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ElsIfStmt!\n");
    exit(1);
  }
}

void visitWhile(While p)
{
  switch(p->kind)
  {
  case is_While1:
    /* Code for While1 Goes Here */
    visitExpressaoLogica(p->u.while1_.expressaologica_);
    visitBlocoStmt(p->u.while1_.blocostmt_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing While!\n");
    exit(1);
  }
}

void visitFor(For p)
{
  switch(p->kind)
  {
  case is_For1:
    /* Code for For1 Goes Here */
    visitAtribuicao(p->u.for1_.atribuicao_);
    visitRExpr(p->u.for1_.rexpr_);
    visitBlocoStmt(p->u.for1_.blocostmt_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing For!\n");
    exit(1);
  }
}

void visitCase(Case p)
{
  switch(p->kind)
  {
  case is_CaseCaseStmt:
    /* Code for CaseCaseStmt Goes Here */
    visitCaseStmt(p->u.casecasestmt_.casestmt_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Case!\n");
    exit(1);
  }
}

void visitCaseStmt(CaseStmt p)
{
  switch(p->kind)
  {
  case is_CaseStmt1:
    /* Code for CaseStmt1 Goes Here */
    visitIdent(p->u.casestmt1_.ident_);
    visitBlocoStmt(p->u.casestmt1_.blocostmt_);
    break;
  case is_CaseStmt2:
    /* Code for CaseStmt2 Goes Here */
    visitBlocoStmt(p->u.casestmt2_.blocostmt_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CaseStmt!\n");
    exit(1);
  }
}

void visitType(Type p)
{
  switch(p->kind)
  {
  case is_Type_INTEGER:
    /* Code for Type_INTEGER Goes Here */
    break;
  case is_Type_REAL:
    /* Code for Type_REAL Goes Here */
    break;
  case is_Type_CHAR:
    /* Code for Type_CHAR Goes Here */
    break;
  case is_Type_STRING:
    /* Code for Type_STRING Goes Here */
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Type!\n");
    exit(1);
  }
}

void visitOperadoresLogicos(OperadoresLogicos p)
{
  switch(p->kind)
  {
  case is_OperadoresLogicos1:
    /* Code for OperadoresLogicos1 Goes Here */
    break;
  case is_OperadoresLogicos2:
    /* Code for OperadoresLogicos2 Goes Here */
    break;
  case is_OperadoresLogicos3:
    /* Code for OperadoresLogicos3 Goes Here */
    break;
  case is_OperadoresLogicos4:
    /* Code for OperadoresLogicos4 Goes Here */
    break;
  case is_OperadoresLogicos5:
    /* Code for OperadoresLogicos5 Goes Here */
    break;
  case is_OperadoresLogicos6:
    /* Code for OperadoresLogicos6 Goes Here */
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OperadoresLogicos!\n");
    exit(1);
  }
}

void visitConectivosLogicos(ConectivosLogicos p)
{
  switch(p->kind)
  {
  case is_ConectivosLogicos_AND:
    /* Code for ConectivosLogicos_AND Goes Here */
    break;
  case is_ConectivosLogicos_OR:
    /* Code for ConectivosLogicos_OR Goes Here */
    break;
  case is_ConectivosLogicos_NOT:
    /* Code for ConectivosLogicos_NOT Goes Here */
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ConectivosLogicos!\n");
    exit(1);
  }
}

void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
  printf("asdasd: %s\n",i);
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}

